version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      - run:
          name: Docker Build
          command: docker build -t petronetto/py3-builder .
      - run:
          name: Push the develop tag
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              docker tag petronetto/py3-builder petronetto/py3-builder:develop
              docker push petronetto/py3-builder:develop
            fi
      - run:
          name: Push the latest tag
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag petronetto/py3-builder petronetto/py3-builder:latest
              docker push petronetto/py3-builder:latest
            fi
      - run:
          name: Backup tag
          command: |
            docker tag petronetto/py3-builder petronetto/py3-builder:v-$CIRCLE_BUILD_NUM
            docker push petronetto/py3-builder:v-$CIRCLE_BUILD_NUM
